spring.application.name=studentSystem
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/StudentDB
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true 


server.servlet.context-path=/api/v1


#security config
#spring.security.user.name=admin
#spring.security.user.password=1234



jwt.secretKey = hbdhfbryg8747gugsyg47gwiujsd8d37uiojjbdyeg563tfrdsws43455t789plomjbvcds3w3456g7ghuyg6tyghfgdyr7y457eguygh67typed